import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Level Up Loot Hub",
  description: "Generated by create next app, created by FumiMelvinDev",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="h-full scroll-smooth antialiased"
      suppressHydrationWarning
    >
      <body className={`${inter.className} flex h-full flex-col`}>
        <Navbar />
        <main className="grow">{children}</main>
      </body>
    </html>
  );
}
